services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3010:3010"
    command: ["npm", "run", "dev"]
    networks:
      - server-shared
    environment:
      - NUXT_GQL_HOST=http://app:5050/query
      - NUXT_PUBLIC_GQL_HOST=http://localhost:5050/query

volumes:
  node_modules:

networks:
  server-shared:
    external: true
    name: server_default
