root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./server.go"
  bin = "tmp/server"
  delay = 2000
  exclude_dir = ["terraform", "proto", ".github", "docker", "doc", ".github"]
  exclude_file = ["docker-compose.yml", "Makefile", "README.md"]
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient --check-go-version=false exec --continue ./tmp/server"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 500
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  poll = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
